name = "TAKATAKA 2K26"
author = "Firo"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39bc12fc95afb68e1caddaefa44a6e7c4349cdf3eb0a8c222b9a8bc807cff0de"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
