name = "TAKATAKA 2K26"
author = "Firo"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5000d7a5f27739458e9a34f8745d2ca4d979f2319fd781df4e90df0dd954e1a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
