name = "TAKATAKA 2K26"
author = "Firo"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "488dfaeab31bad39be98339ac3039c216f4c5eddc14a701d6bc5a2105b987faf"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
